[project]
name = "large-file-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "taupirho", email = "thomas.reid@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "psutil>=7.2.2",
]

[project.scripts]
large-file-tests = "large_file_tests:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
